// Farm safety assessment question bank.
// Each question: single correct answer (index). `critical: true` questions are
// safety-critical and must ALL be correct to pass, regardless of overall score.
window.ASSESSMENT = {
  passOverall: 0.8, // 80% of all questions
  questions: [
    {
      topic: "Safe Stop", critical: true,
      q: "What are the four steps of the Safe Stop procedure, in order?",
      options: [
        "Engine off → key out → handbrake → neutral",
        "Handbrake on → controls in neutral → engine off → key out",
        "Neutral → engine off → handbrake → leave key in",
        "Lower the loader → engine off → walk away → handbrake",
      ],
      answer: 1,
      explain: "Brake — Neutral — Off — Out. Do it before leaving the seat, before anyone approaches, and before touching the machine.",
    },
    {
      topic: "Safe Stop", critical: true,
      q: "A baler is blocked. What must you do before clearing it?",
      options: [
        "Reach in quickly while it idles — it only takes a second",
        "Disengage the PTO but leave the engine running so you can restart fast",
        "Safe Stop, take the key, and wait until ALL moving parts have completely stopped",
        "Ask someone to feed it through by hand while you watch",
      ],
      answer: 2,
      explain: "Moving parts coast on for several seconds. Stop everything, key in pocket, wait for all movement to stop, then clear with a tool.",
    },
    {
      topic: "Safe Stop",
      q: "Roughly what share of run-over deaths on farms could be prevented just by using the handbrake?",
      options: ["About 10%", "About 30%", "About 60%", "Almost none"],
      answer: 2,
      explain: "HSE found around 60% of run-over deaths could have been prevented simply by putting the handbrake on.",
    },
    {
      topic: "The big killers",
      q: "Which is the single biggest cause of death on UK farms?",
      options: ["Livestock", "Transport (run-over, overturns, crushing)", "Falls from height", "Electrocution"],
      answer: 1,
      explain: "Transport — being run over, machines overturning, and crushing — is consistently the leading cause.",
    },
    {
      topic: "Tractors", critical: true,
      q: "Why do you drive a tractor up and down a slope rather than across it?",
      options: [
        "It is faster",
        "To avoid a sideways overturn",
        "It uses less fuel",
        "It is easier on the tyres",
      ],
      answer: 1,
      explain: "Driving across a slope risks a sideways rollover. Up and down keeps the centre of gravity stable.",
    },
    {
      topic: "Tractors", critical: true,
      q: "Why must you never hitch a load high up on the tractor instead of at the drawbar?",
      options: [
        "It looks untidy",
        "It can make the tractor rear up and roll over backwards",
        "It wastes hydraulic oil",
        "It is fine as long as you go slowly",
      ],
      answer: 1,
      explain: "Hitching high causes the tractor to rear and flip backwards under load. Always hitch at the drawbar/proper point.",
    },
    {
      topic: "Tractors",
      q: "If a tractor with a cab/ROPS and seatbelt starts to overturn, you should:",
      options: [
        "Jump clear as fast as you can",
        "Stay in the seat, hold on, and lean away from the fall",
        "Stand up to brace yourself",
        "Open the door and step out",
      ],
      answer: 1,
      explain: "The cab/frame and belt protect you. Jumping out usually means being crushed under the tractor.",
    },
    {
      topic: "Tractors",
      q: "At 16, on a public road, you may drive a tractor only if it is:",
      options: [
        "Any size, with any licence",
        "Up to 2.45 m wide, with a Category F licence",
        "Under 5 tonnes, no licence needed",
        "Towing no more than two trailers",
      ],
      answer: 1,
      explain: "At 16 you need a Category F licence and the tractor (and trailer) must be no more than 2.45 m wide. The width limit lifts at 17.",
    },
    {
      topic: "Telehandlers", critical: true,
      q: "What happens to a telehandler's safe lifting capacity as the boom is raised and extended forward?",
      options: [
        "It stays the same at all positions",
        "It increases",
        "It drops sharply — you must read the load chart",
        "It only matters on slopes",
      ],
      answer: 2,
      explain: "Capacity falls steeply with height and reach. Always work to the load chart in the cab.",
    },
    {
      topic: "Telehandlers", critical: true,
      q: "How should you travel with a load on the telehandler?",
      options: [
        "Boom raised high so you can see the load",
        "Load low, boom retracted and tilted back",
        "Boom fully extended forward",
        "However is quickest across the yard",
      ],
      answer: 1,
      explain: "Carry the load LOW with the boom in. A raised load while moving is the classic way to tip a telehandler.",
    },
    {
      topic: "Telehandlers", critical: true,
      q: "The telehandler boom contacts an overhead power line. What is the safest action?",
      options: [
        "Jump out immediately and run",
        "Get out and push the boom off the line",
        "Stay in the cab, drive clear if you can, keep everyone back, and call for help",
        "Touch the boom to check if it is live",
      ],
      answer: 2,
      explain: "Stay in the cab (safest), reverse/lower clear if possible, keep everyone away, call 999 and the network (105). Only jump clear — feet together — if forced out by fire.",
    },
    {
      topic: "Telehandlers",
      q: "Can a 16-year-old operate the telehandler?",
      options: [
        "Yes, anywhere including public roads",
        "No, never under 18",
        "Yes — on private land only, if trained, competent, mature and supervised; not on a public road",
        "Only the small one, with no training",
      ],
      answer: 2,
      explain: "On private farmland only, with accredited training, competence, maturity and adequate supervision. Road use is not for a 16-year-old.",
    },
    {
      topic: "Bale handling", critical: true,
      q: "Why must you never move round bales with the loader bucket?",
      options: [
        "It scratches the bucket",
        "Bales can roll back down the loader arms toward the cab and operator",
        "It is slower than a grab",
        "The bucket is too small",
      ],
      answer: 1,
      explain: "Use a bale spike or grab. A bucket lets the bale roll back onto the operator.",
    },
    {
      topic: "Bale handling",
      q: "When building a bale stack you should:",
      options: [
        "Stack as tall and narrow as possible to save space",
        "Build square and bonded on firm level ground, not too tall, clear of power lines — and never climb it",
        "Lean it against a building for support",
        "Pull bales from the bottom when taking it down",
      ],
      answer: 1,
      explain: "Stable bonded stacks on firm ground; never climb a stack; take stacks down from the top.",
    },
    {
      topic: "PTO & machinery", critical: true,
      q: "A guard on a machine is broken or missing. What do you do?",
      options: [
        "Run it carefully and avoid the gap",
        "Tape over the gap and carry on",
        "Take the machine out of use and report it — do not run it",
        "Remove the other guards too so it is balanced",
      ],
      answer: 2,
      explain: "Never run a machine with a missing or damaged guard. Take it out of use and tell your supervisor.",
    },
    {
      topic: "PTO & machinery", critical: true,
      q: "Why must loose clothing, cords and jewellery be removed or tied up around machinery?",
      options: [
        "It looks more professional",
        "They can be caught by rotating parts and drag you in",
        "It keeps you cooler",
        "Only long hair is a real risk",
      ],
      answer: 1,
      explain: "A loose drawstring or sleeve caught by a PTO shaft can pull you in. Tuck in clothing, tie back hair, remove jewellery.",
    },
    {
      topic: "Mowers",
      q: "Before mowing with the disc mowers you should:",
      options: [
        "Just start cutting — the discs handle anything",
        "Walk/check the field for stones, wire and debris, and keep people clear of the throw line",
        "Remove the protective curtains for a cleaner cut",
        "Run them at full PTO speed from cold",
      ],
      answer: 1,
      explain: "Discs throw stones and broken blade pieces a long way. Clear the field of hazards and keep bystanders well clear.",
    },
    {
      topic: "Baler",
      q: "The most dangerous part of the New Holland BB940A when running is:",
      options: [
        "The drawbar",
        "The plunger and the stored energy in the flywheel",
        "The twine box",
        "The road lights",
      ],
      answer: 1,
      explain: "The plunger rams with lethal force and the flywheel coasts a long time. Never reach into the chamber/pick-up; wait for the flywheel to fully stop.",
    },
    {
      topic: "Fuelling",
      q: "AdBlue (DEF) should be:",
      options: [
        "Poured into the diesel tank to clean it",
        "Put only in the separate blue-capped tank — never mixed with diesel",
        "Mixed 50/50 with diesel",
        "Ignored, it is optional",
      ],
      answer: 1,
      explain: "AdBlue goes in its own blue filler only. Mixing it with diesel (either way) causes expensive damage.",
    },
    {
      topic: "Fuelling",
      q: "When refuelling diesel you should:",
      options: [
        "Leave the nozzle running and go do another job",
        "Fill right to the brim on hot days",
        "Engine off, no smoking, hold the nozzle, and stop before it overflows",
        "Refuel with the engine running to save time",
      ],
      answer: 2,
      explain: "Engine off and Safe Stop, no ignition sources, stay with the nozzle, don't overfill — diesel expands and spills are a fire and pollution risk.",
    },
    {
      topic: "Greasing & maintenance", critical: true,
      q: "Before greasing or doing any maintenance on a machine you must:",
      options: [
        "Leave it running so you can test as you go",
        "Safe Stop and put the key in your pocket so no one can start it",
        "Just engage the handbrake",
        "Ask someone to sit in the cab and hold the brake",
      ],
      answer: 1,
      explain: "Safe Stop, key in your pocket, and wait for all parts to stop. Most maintenance deaths happen on machines that were running or could move.",
    },
    {
      topic: "Manual handling",
      q: "The correct way to lift a heavy object is to:",
      options: [
        "Bend your back and lift quickly",
        "Bend your knees, keep the load close, lift with your legs, and don't twist",
        "Twist as you lift to save a step",
        "Hold the load at arm's length",
      ],
      answer: 1,
      explain: "Knees not back, load close to the body, no twisting — and use a machine or get help for anything heavy.",
    },
    {
      topic: "Health",
      q: "'Farmer's Lung' is caused by, and avoided by:",
      options: [
        "Cold weather; avoided by wearing a coat",
        "Mould spores in hay; avoided by wearing an FFP3 mask and not disturbing mouldy bales unmasked",
        "Loud noise; avoided by ear defenders",
        "Diesel fumes; avoided by working outdoors",
      ],
      answer: 1,
      explain: "It's a serious lung disease from breathing hay mould spores. Wear a proper dust mask and work upwind of dust.",
    },
    {
      topic: "Site hazards", critical: true,
      q: "Why must you never walk on an old farm building roof?",
      options: [
        "It voids the warranty",
        "Roofs like fibre/asbestos cement and rooflights are fragile — you can fall straight through",
        "It frightens the livestock",
        "It is fine if you step on the bolts",
      ],
      answer: 1,
      explain: "Fragile roofs kill. Falling through a roof is a specialist job with proper equipment — never walk on one.",
    },
    {
      topic: "Site hazards", critical: true,
      q: "What is the rule on slurry tanks, pits and grain stores (confined spaces)?",
      options: [
        "Enter quickly and get out fast",
        "Hold your breath while inside",
        "Never enter — toxic gas, lack of oxygen and engulfment can kill in seconds",
        "Enter only if a friend watches from outside",
      ],
      answer: 2,
      explain: "Confined-space entry needs permits, gas testing and rescue plans — never a job for a young, inexperienced worker. Stay out.",
    },
    {
      topic: "Site hazards",
      q: "Around cattle, especially cows with calves, you should:",
      options: [
        "Move fast and shout to assert yourself",
        "Stay calm, keep an escape route, never get between a cow and her calf, and treat bulls as dangerous",
        "Walk straight through the middle of the herd",
        "Turn your back and ignore them",
      ],
      answer: 1,
      explain: "Cattle are a leading cause of farm deaths. Calm, escape route, never cornered, never between cow and calf.",
    },
    {
      topic: "Emergencies", critical: true,
      q: "Someone is seriously hurt in a far field. After making it safe and checking them, what do you tell 999?",
      options: [
        "Just the farm name and hope they find it",
        "The address/postcode AND what3words, what happened, how many hurt, and injuries — then send someone to the gate",
        "Only your phone number",
        "Nothing — wait for them to ask",
      ],
      answer: 1,
      explain: "Give the postcode (BN5 9LL) and the nearest what3words, what happened, numbers and injuries, and guide the ambulance in from the gate.",
    },
    {
      topic: "Emergencies",
      q: "If you have poor mobile signal in a field during an emergency, you should:",
      options: [
        "Give up and drive to find signal, leaving the casualty",
        "Try 112 — it works on any network and can use any mast",
        "Only send a text to a friend",
        "Wait an hour and try again",
      ],
      answer: 1,
      explain: "112 works across any available network. Know the spots with signal, and if possible send someone for help.",
    },
  ],
};
